device: cuda
run_name: critical-distance-mlp

# model params
model_type: mlp
num_layers: 4
input_dim: 3
hidden_dim: 128
output_dim: 64

# dataset params
train_path: /data/haoyun/shortest-path/norway_500x_critical_distance_train.pt
valid_path: /data/haoyun/shortest-path/norway_500x_random_valid.pt
test_path: /data/haoyun/shortest-path/norway_500x_random_test.pt

# training params 
lr: 1e-4
epoch: 100
batch_size: 256
model_checkpoint: /data/haoyun/shortest-path/model_cache/
num_train_runs: 5