device: cuda
run_name: random-sample-gat

# model params
model_type: gnn
gnn_kind: gat
num_layers: 4
input_dim: 3
hidden_dim: 128
output_dim: 16

# dataset params
train_path: /data/haoyun/shortest-path/norway_500x_random_train.pt
valid_path: /data/haoyun/shortest-path/norway_500x_random_valid.pt
test_path: /data/haoyun/shortest-path/norway_500x_random_test.pt

# training params 
lr: 1e-3
epoch: 100
batch_size: 256
model_checkpoint: /data/haoyun/shortest-path/model_cache/
pretrain_path: /data/haoyun/shortest-path/model_cache/random-sample-gat/best.pt